<?php

/**
 * @file
 * Create reset password email OTP functions.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function reset_password_email_otp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.reset_password_email_otp':
      $output = '';
      $output .= '<h3>' . t('Existing Approach') . '</h3>';
      $output .= '<p>' . t("Drupal by default sends Password Reset URL by email to user's email id in password recovery mail, but Reset Password Email OTP module sends random generated OTP by email instead of URL to the user.") . '</p>';
      $output .= '<h3>' . t('Whats new in this module') . '</h3>';
      $output .= '<p>' . t("Reset Password Email OTP Module provide a block to enter username or email of the user and send OTP on his email for verification. Once OTP verification completed this module allow user to enter new password.") . '</p>';
      $output .= '<dl>';
      $output .= '<h3>' . t('Module Configuration Steps:') . '</h3>';
      $output .= '<dd>' . t("After enabling the module, Go to the path : /admin/config/people/reset-password-email-otp") . '</dd>';
      $output .= '<dd>' . t("Set configuration for OTP length, wrong attempt limit and mail template.") . '</dd>';
      $output .= '<dd>' . t("Make sure in Email Body template [OTP] must be there.") . '</dd>';
      $output .= '<dd>' . t("Save form configuration.") . '</dd>';
      $output .= '<h3>' . t('How to use:') . '</h3>';
      $output .= '<dd>' . t("Go to the 'Block layout' page (under Structure) and use any of the 'Place block' buttons to create a Reset Password Email OTP Form block.") . '</dd>';
      $output .= '<dd>' . t("save that block.") . '</dd>';
      $output .= '</dl>';

      return $output;
  }
}
