reset_password_email_otp.config-settings:
  type: mapping
  label: Settings
  mapping:
    reset_password_email_otp_wrong_attempt:
      type: integer
      label: 'Wrong attempt OTP'
    reset_password_email_otp_length:
      type: integer
      label: 'OTP length'
    reset_password_email_otp_mail_subject:
      type: text
      label: 'Reset OTP mail subject'
    reset_password_email_otp_mail_body:
      type: text
      label: 'Reset OTP mail body'
